-- Insert Data into ITEM_DETAILS Table
INSERT INTO ITEM_DETAILS VALUES (1, 'Item1', 10);
INSERT INTO ITEM_DETAILS VALUES (2, 'Item2', 35);
INSERT INTO ITEM_DETAILS VALUES (3, 'Item3', 50);
INSERT INTO ITEM_DETAILS VALUES (4, 'Item4', 5);
INSERT INTO ITEM_DETAILS VALUES (5, 'Item5', 2);
INSERT INTO ITEM_DETAILS VALUES (6, 'Item6', 10);
INSERT INTO ITEM_DETAILS VALUES (7, 'Item7', 180);







